# Please refer to https://scipy.github.io/devdocs/building/index.html
# To use:
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate scipy-dev
#
name: scipy-dev-py313
channels:
  - conda-forge
dependencies:
  - python==3.13
  - cython>=3.2.0
  - c-compiler
  - cxx-compiler
  - meson
  - meson-python
  - ninja
  - numpy
  - openblas
  - pkg-config
  - libblas=*=*openblas  # helps avoid pulling in MKL
  - pybind11
  # scipy.datasets dependency
  - pooch
  # ---
  - pythran
  # For testing and benchmarking
  - pytest>=8.0.0
  - pytest-cov
  - pytest-xdist
  - pytest-timeout
  - asv >=0.6
  - conda-build
  - hypothesis
  - array-api-strict>=2.3.1
  # For type annotations
  - mypy
  - pyrefly
  - typing_extensions
  - types-psutil
  # For building docs
  - ipython
  - threadpoolctl
  - scipy-doctest>=2.0.0
  # For CLI
  - spin
  - click<8.3.0  # transitive dependency of `spin`, 8.3.0 is breaking (see gh-23642)
  # For linting
  - ruff>=0.12.0
  - cython-lint
#
  - pytorch
  - jax
  - jaxlib=*=*cuda*
  - cupy
  - numba
