name: macOS BLAS ILP64 tests

on:
  push:
    branches:
      - maintenance/**
  pull_request:
    branches:
      - main
      - maintenance/**

permissions:
   contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  accelerate:
    name: Accelerate (ILP64)
    if: "github.repository == 'ev-br/scipy'"
    runs-on: macos-15
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Build and Install SciPy
      run: |
        sudo xcode-select -s /Applications/Xcode_16.app

        git submodule update --init
        GFORTRAN_LOC=$(which gfortran-13)
        ln -s $GFORTRAN_LOC gfortran
        export PATH=$PWD:$PATH

        # Ensure we have gfortran dylib
        GFORTRAN_LIB=$(dirname `gfortran --print-file-name libgfortran.dylib`)
        export DYLD_LIBRARY_PATH=$GFORTRAN_LIB

        pip install click doit pydevtool rich_click meson cython pythran pybind11 ninja numpy
        python dev.py build -C-Dblas=accelerate -C-Duse-ilp64=true

        pip install pooch pytest hypothesis
        python dev.py -n test
